add vivaldi in the README
getomni/omni pull request #19
Opened 2021-02-24 20:28 UTC by ThiagoG8

2021-02-24 20:37 UTC, ThiagoG8 commented
I am waiting for the approval of the PR and it is an honor to contribute to the Omni theme!

2021-02-24 21:02 UTC, jpedroschmitz requested changes

2021-02-24 21:02 UTC, jpedroschmitz commented on README.md
> +- [Vivaldi](https://github.com/getomni/Vivaldi)
Hey, thanks for opening the PR!

Could you place Vivaldi on the end of this browser list? We are ordering the themes alphabetically

2021-02-24 21:03 UTC, jpedroschmitz commented
> I am waiting for the approval of the PR and it is an honor to contribute to the Omni theme!

Hey, thanks for opening the PR and for contributing to Omni!

I have reviewed it and requested a small change to keep the pattern on the list

2021-02-25 18:49 UTC, jpedroschmitz approved these changes

2021-02-25 18:52 UTC, merged